---
title: "Python Final Report"
date: last-modified
author: "Hayden Coke and Bekah Peterson"
format:
  html:
    embed-resources: true
execute: 
  echo: false
  warning: false
jupyter: python3
---

# Patterns in Healthcare Spending from 1980 to 2014

## Introduction / Background

Healthcare spending is a growing concern for most Americans. The US spends more than twice as much per capita on health care as other developed countries (Pahlka, 2023). One in ten Americans has at least $250 in medical debt. The majority of Americans with $10,000 or more in debt do not think they will ever be able to pay it off. Families of middle- or lower-income status are especially burdened by medical debt (Surg, 2025).

This report will seek to answer the question: How has healthcare spending changed over time? 

This question can be further broken down by examining trends in healthcare spending among states/regions and spending items, such as hospital care and medical products.

Understanding how healthcare spending has changed over time reveals not only the financial burden on households, but also the strain on public budgets and the economy. Tracking these trends helps policymakers identify whether spending growth is sustainable, whether resources are being allocated efficiently, and how disparities across regions or income groups may be widening. Additionally, trends based on spending items inform which categories differ from others.

## Methods

To answer this question, we examined a dataset of healthcare spending from 1980 to 2014 that reported individual-state spending and spending by item category. Dr. Gore provided us with a census dataset, which we used to match states and years to their corresponding populations. To account for inflation, we adjusted the spending amounts in the original dataset using the Python package cpi by Palewire, which uses the Consumer Price Index. After adjusting for inflation, we calculated spending per capita by dividing the spending by the state population. Per-capita analysis ensured that states with higher populations could be compared to states with lower populations more effectively.

`Spending per capita = (spending adjusted for inflation) / (state population)`

Healthcare items reported by this dataset include: Hospital Care; Physician & Clinical Services; Other Professional Services; Dental Services; Home Health Care; Prescription Drugs; Durable Medical Products; Other Non-durable Medical Products; Nursing Home Care; and Other Health, Residential, and Personal Care. The CDC defines Personal Healthcare Spending as "payments for goods and services directly relating to patient care", which we have interpreted as the sum of all healthcare spending categories (Healthcare Spending, 2025). This is supported by the total spending in the Personal Health Care category closely matching the combined total spending in all other categories. To visualize the trend in spending over time by item, a line plot was created with the year as the explanatory variable and the inflation-adjusted spending in millions of dollars as the response, color-coded by item (Fig 1).

Because representing every state on one graph would be visually difficult to interpret, we chose to create a figure representing regions rather than states to visualize regional spending. A line plot was created with the year as the explanatory variable, spending per capita in millions of dollars as the response variable, and color-coded by region (Fig 2). Washington DC was excluded from this figure because its spending was an outlier. Upon noticing Washington DC's high spending, we created a scatterplot with the year as the explanatory variable, spending per capita in millions of dollars as the response variable, and color-coded by item (Fig 3).

Sklearn was used to create a multi linear regression model using population and year as explanatory variables (features) and inflation-adjusted spending as the response variable. The motivation behind this model was to determine if we could predict a state's spending based on its population during a given year. Population and spending had a correlation coefficient of 0.96; year and spending had a lower correlation coefficient of 0.21; both produced p-values of less than 0.01. The variance inflation factor (VIF) of these features were both close to 1, indicating an absence of multicolinearity. Both features were scaled to have a mean of 0 and a standard deviation of 1, which standardized their ranges. The dataset was then split into test data and training data at a proportion of 80% training data, which was used to fit the model, and 20% test data, which was used to evaluate the model's accuracy. After fitting, the model produced an R-squared of 0.94 and slope coefficients of 57940.08 and 8540.23 for population and year. Plots of residuals (Fig 4) and predicted vs. actual values (Fig 5) were created to visually assess model fit, and a Quantile-Quantile plot was created to assess normality of the features (Fig 6).

## Results

As seen in Table 1, thirty-four states have experienced a cost percent change of more than 200% between 1980 and 2014. New Hampshire and Vermont have experienced a percent change of more than 300%. There is some regional connection among the states with the greatest or least percent changes. Among the 5 states that experienced the greatest increase, 3 are in New England. Among the 5 states that experienced the least increase, 3 are in the Southwest. This points to a possible economic or political difference in these regions compared to others. Data on healthcare policies and laws for each region would be needed to confirm any connections.

Inspecting spending per capita by year, it appears that every region roughly follows the same trend of increasing somewhat linearly over time (Fig 2). Despite following the same general shape, the difference between each region increases over time, with New England spending the most and the Rocky Mountains and Southwest spending the least by 2014. This agrees with the percent changes found in Table 1.

As mentioned, Washington DC was excluded from Figure 2 because of its disproportionate influence on the Mideast. This is explained by DC's high spending on Hospital Care. Aside from this item, other items follow similar patterns to other states, which suggests that DC spends more on hospital care than other states.

The residual plot of the model does not indicate homoscedasticity (Fig 4). The predicted vs actual values closely follows the y = x line, with a few points deviating from the line around the median (Fig 5). Most points that closely follow the line are in the lower range of the data, implying better fit in the lower ranges. The Quantile-Quantile plot shows an S-shaped pattern, indicating that the data is not normally distributed (Fig 6). Considering these diagnostics, this model is not very useful for its intended purpose of predicting spending. Some improvements would be to make separate models for each state rather than using data from the whole country, or further narrowing the question by creating models specific to each item by state. 

## Conclusion

In our exploration of spending patterns, we found that healthcare spending is increasing at a rate that outpaces inflation. The District of Columbia is an outlier for high spending, largely due to its very high hospital care costs. More research and analysis are needed to explain why DC hospitals are so much more expensive than those in other states. DC is the most expensive “state” to live in, but that does not fully explain why hospital care in particular is more expensive. They may have care laws that are driving up prices, such as requiring patients to pay out of pocket for services that are covered in other states or requiring expensive tests that are not required in other states.

Undercoverage bias could potentially be impacting our data. We know that our data represents healthcare spending in the US, but we don't know how that money is being counted. Is it measured by insurance claims, state spending, individual out of pocket, or some combination thereof. Additionally, if a patient pays their bill with a personal loan or credit card, that debt is not recorded as medical debt. Debt is not the same as spending, but since we do not know how our data was collected, this could contribute to some missingness.

This data set does not include any information from the last 11 years. We know that health care spending continued to increase, especially after COVID-19. Further research could explore how spending has changed since 2020, identifying where costs are growing fastest, both by region and category.

## References

Consumer Price Index. (n.d.). Retrieved from U.S. Bureau of Labor Statistics: https://www.bls.gov/cpi/

cpi. (2025). Retrieved from palewire: https://palewi.re/docs/cpi/

Healthcare Spending. (2025, August 8). Retrieved from National Center for Health Statistics: https://www.cdc.gov/nchs/dqs/topics/healthcare-spending.html

Pahlka, J. (2023). [Re]Coding America: Why Government Is Failing in the Digital Age and How We Can Do Better. New York, New York: Macmillan.

Surg, A. M. (2025, January 21). Healthcare debts in the United States: a silent fight. Retrieved from NIH: National Library of Medicine: https://pmc.ncbi.nlm.nih.gov/articles/PMC11918610/


## Appendix

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import PredictionErrorDisplay, mean_squared_error, r2_score
from scipy.stats import probplot, pearsonr
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

df_all = pd.read_csv("./datasets/healthcare_spending_states.csv")
df_personal = df_all[df_all['Item'] == 'Personal Health Care (Millions of Dollars)']
df_items = df_all[df_all['Item'] != 'Personal Health Care (Millions of Dollars)']

# df_personal['Spending'].sum() - df_items['Spending'].sum()
# it's off by 6 (million) but that's really small
```

**Table 1.** Percent growth on healthcare spending (measured in millions of dollars per capita) among states from 1980 to 2014. 

```{python}
# percent changes from 1980 to 2014 by state
df_2014 = df_personal[df_personal['Year'] == 2014]
df_1980 = df_personal[df_personal['Year'] == 1980]

spending_2014 = df_2014.groupby('State', as_index=False)['perCapSpendAdjusted'].sum()
spending_2014.rename(columns={'perCapSpendAdjusted': 'Spending Per Capita in 2014'}, inplace=True)

spending_1980 = df_1980.groupby('State', as_index=False)['perCapSpendAdjusted'].sum()
spending_1980.rename(columns={'perCapSpendAdjusted': 'Spending Per Capita in 1980'}, inplace=True)

delta = spending_1980.merge(spending_2014, on='State', how='left')
delta['Percent Change'] = (delta['Spending Per Capita in 2014'] - delta['Spending Per Capita in 1980']) / delta['Spending Per Capita in 1980'] * 100

delta.sort_values(by='Percent Change', inplace=True, ascending=False, ignore_index=True)

pd.options.display.float_format = '{:.5f}'.format
delta['Percent Change'] = delta['Percent Change'].apply(lambda x: '{:.2f}%'.format(x))

display(delta)
```


```{python}
# spending by item over time
sns.lineplot(df_items, x='Year', y='SpendAdjust', hue='Item')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)
plt.xlabel("Year")
plt.ylabel("Millions of Dollars")
plt.show()
```

**Fig 1.** Spending in Millions of Dollars by Item (1980-2014). 

```{python}
# spending per capita by region (exluding DC)
df_personal_noDC = df_personal[df_personal['State'] != 'District of Columbia']
sns.lineplot(df_personal_noDC, x = 'Year', y = 'perCapSpendAdjusted', hue='Region_Name')
plt.xlabel("Year")
plt.ylabel("Spending per Capita in Millions of Dollars")
plt.show()
```

**Fig 2.** Spending per Capita in Millions of Dollars by Year per Region, DC excluded (1980-2014). 

```{python}
dc_only = df_items[df_items['State'] == 'District of Columbia']
sns.scatterplot(dc_only, x='Year', y='perCapSpendAdjusted', hue='Item')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)
plt.xlabel("Year")
plt.ylabel("Spending per Capita in Millions of Dollars")
plt.show()
```

**Fig 3.** Spending per Capita in Millions of Dollars by Year in Washington DC (1980-2014). 

```{python}
# Can we predict the spending of a state when given its year and population?

# correlation coefficients
pop_spend_pearson = pearsonr(df_personal['Population'], df_personal['SpendAdjust'])
year_spend_pearson = pearsonr(df_personal['Year'], df_personal['SpendAdjust'])

x = df_personal[['Population', 'Year']]
y = df_personal['SpendAdjust']

# scale x values
x_scaled = StandardScaler().fit_transform(x)

# split into training and test
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=501)

# fit model
model = LinearRegression().fit(x_train, y_train)
y_pred = model.predict(x_test)

# checking fit
# print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
# print("R-squared:", r2_score(y_test, y_pred))
# print("score:", model.score(x, y))
# print("coef:", model.coef_)

# Mean Squared Error: 190187697.61533767
# R-squared: 0.9441692527769192
# score: -69539525570452.625
# coef: [57940.08517601  8540.2302216 ]

# Add a constant to the model
x_train_sm = sm.add_constant(x_train)
model_sm = sm.OLS(y_train, x_train_sm).fit()
# print(model_sm.summary())

# VIF
vif_data = pd.DataFrame()
vif_data['Feature'] = ['Population', 'Year']
vif_data['VIF'] = [variance_inflation_factor(x_scaled, i) for i in range(x_scaled.shape[1])]

# print(vif_data)
#       Feature     VIF
# 0  Population 1.00504
# 1        Year 1.00504
```

```{python}
# Residual Plot
residuals = y_test - y_pred
plt.scatter(y_pred, residuals, alpha=0.5)
plt.xlabel('Predicted Values')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.axhline(y=0, color='red', linestyle='--')
plt.show()
```

**Fig 4.** Plot of residuals for the multi linear regression model.

```{python}
# Predicted vs Actual Plot
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.title('Predicted vs Actual Values')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=4)
plt.show()
```

**Fig 5.** Plot of predicted vs. actual values for the multi linear regression model.

```{python}
# Q-Q Plot for residuals
sm.qqplot(model_sm.resid, line='s')
plt.title('Q-Q Plot of Residuals')
plt.show()
```

**Fig 6.** Quantile-Quantile plot for the multi linear regression model.

```{python}
# can we plot it?
plt.figure(figsize=(8, 6))
axes = plt.axes(projection="3d")
axes.scatter3D(df_personal['Population'], df_personal['Year'], df_personal['SpendAdjust'])
axes.set_xlabel("Population")
axes.set_ylabel("Year")
axes.set_zlabel("Speanding")

plt.show()
```

**Fig 7.** 3D scatterplot of Population, Year, and Spending (adjusted for inflation).